"""empty message

Revision ID: 73743ed30882
Revises: 3c821ae8a578
Create Date: 2020-06-13 21:41:27.695204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73743ed30882'
down_revision = '3c821ae8a578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
